version: '3.8'
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
      - ./tmp:/app/tmp
    env_file:
      - .env
    depends_on:
      - redis
      - elasticsearch

  worker:
    build: .
    command: celery -A services.async_service.celery_app.celery worker --loglevel=info
    volumes:
      - ./src:/app/src
      - ./tmp:/app/tmp
    env_file:
      - .env
    depends_on:
      - redis
      - elasticsearch

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
